//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/ontai-dev/seam-core/pkg/lineage"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIEndpoint) DeepCopyInto(out *APIEndpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIEndpoint.
func (in *APIEndpoint) DeepCopy() *APIEndpoint {
	if in == nil {
		return nil
	}
	out := new(APIEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureCluster) DeepCopyInto(out *SeamInfrastructureCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureCluster.
func (in *SeamInfrastructureCluster) DeepCopy() *SeamInfrastructureCluster {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureClusterList) DeepCopyInto(out *SeamInfrastructureClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamInfrastructureCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureClusterList.
func (in *SeamInfrastructureClusterList) DeepCopy() *SeamInfrastructureClusterList {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureClusterSpec) DeepCopyInto(out *SeamInfrastructureClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureClusterSpec.
func (in *SeamInfrastructureClusterSpec) DeepCopy() *SeamInfrastructureClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureClusterStatus) DeepCopyInto(out *SeamInfrastructureClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureClusterStatus.
func (in *SeamInfrastructureClusterStatus) DeepCopy() *SeamInfrastructureClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachine) DeepCopyInto(out *SeamInfrastructureMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachine.
func (in *SeamInfrastructureMachine) DeepCopy() *SeamInfrastructureMachine {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineList) DeepCopyInto(out *SeamInfrastructureMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamInfrastructureMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineList.
func (in *SeamInfrastructureMachineList) DeepCopy() *SeamInfrastructureMachineList {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineSpec) DeepCopyInto(out *SeamInfrastructureMachineSpec) {
	*out = *in
	out.TalosConfigSecretRef = in.TalosConfigSecretRef
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineSpec.
func (in *SeamInfrastructureMachineSpec) DeepCopy() *SeamInfrastructureMachineSpec {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineStatus) DeepCopyInto(out *SeamInfrastructureMachineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineStatus.
func (in *SeamInfrastructureMachineStatus) DeepCopy() *SeamInfrastructureMachineStatus {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineTemplate) DeepCopyInto(out *SeamInfrastructureMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineTemplate.
func (in *SeamInfrastructureMachineTemplate) DeepCopy() *SeamInfrastructureMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineTemplateList) DeepCopyInto(out *SeamInfrastructureMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamInfrastructureMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineTemplateList.
func (in *SeamInfrastructureMachineTemplateList) DeepCopy() *SeamInfrastructureMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamInfrastructureMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineTemplateResource) DeepCopyInto(out *SeamInfrastructureMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineTemplateResource.
func (in *SeamInfrastructureMachineTemplateResource) DeepCopy() *SeamInfrastructureMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamInfrastructureMachineTemplateSpec) DeepCopyInto(out *SeamInfrastructureMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamInfrastructureMachineTemplateSpec.
func (in *SeamInfrastructureMachineTemplateSpec) DeepCopy() *SeamInfrastructureMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(SeamInfrastructureMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
