//go:build !ignore_autogenerated

package v1alpha1

import (
	"github.com/ontai-dev/seam-core/pkg/lineage"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *ClusterLog) DeepCopyInto(out *ClusterLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *ClusterLog) DeepCopy() *ClusterLog {
	if in == nil {
		return nil
	}
	out := new(ClusterLog)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterLogList) DeepCopyInto(out *ClusterLogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterLog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterLogList) DeepCopy() *ClusterLogList {
	if in == nil {
		return nil
	}
	out := new(ClusterLogList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterLogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterLogSpec) DeepCopyInto(out *ClusterLogSpec) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make(map[string]OperationRecord, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

func (in *ClusterLogSpec) DeepCopy() *ClusterLogSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterLogStatus) DeepCopyInto(out *ClusterLogStatus) {
	*out = *in
}

func (in *ClusterLogStatus) DeepCopy() *ClusterLogStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterLogStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OperationFailureReason) DeepCopyInto(out *OperationFailureReason) {
	*out = *in
}

func (in *OperationFailureReason) DeepCopy() *OperationFailureReason {
	if in == nil {
		return nil
	}
	out := new(OperationFailureReason)
	in.DeepCopyInto(out)
	return out
}

func (in *OperationRecord) DeepCopyInto(out *OperationRecord) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.FailureReason != nil {
		in, out := &in.FailureReason, &out.FailureReason
		*out = new(OperationFailureReason)
		**out = **in
	}
}

func (in *OperationRecord) DeepCopy() *OperationRecord {
	if in == nil {
		return nil
	}
	out := new(OperationRecord)
	in.DeepCopyInto(out)
	return out
}

func (in *CAPIConfig) DeepCopyInto(out *CAPIConfig) {
	*out = *in
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(CAPIControlPlaneConfig)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]CAPIWorkerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CiliumPackRef != nil {
		in, out := &in.CiliumPackRef, &out.CiliumPackRef
		*out = new(CAPICiliumPackRef)
		**out = **in
	}
}

func (in *CAPIConfig) DeepCopy() *CAPIConfig {
	if in == nil {
		return nil
	}
	out := new(CAPIConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *CAPICiliumPackRef) DeepCopyInto(out *CAPICiliumPackRef) {
	*out = *in
}

func (in *CAPICiliumPackRef) DeepCopy() *CAPICiliumPackRef {
	if in == nil {
		return nil
	}
	out := new(CAPICiliumPackRef)
	in.DeepCopyInto(out)
	return out
}

func (in *CAPIControlPlaneConfig) DeepCopyInto(out *CAPIControlPlaneConfig) {
	*out = *in
}

func (in *CAPIControlPlaneConfig) DeepCopy() *CAPIControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(CAPIControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *CAPIWorkerPool) DeepCopyInto(out *CAPIWorkerPool) {
	*out = *in
	if in.SeamInfrastructureMachineNames != nil {
		in, out := &in.SeamInfrastructureMachineNames, &out.SeamInfrastructureMachineNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *CAPIWorkerPool) DeepCopy() *CAPIWorkerPool {
	if in == nil {
		return nil
	}
	out := new(CAPIWorkerPool)
	in.DeepCopyInto(out)
	return out
}

func (in *LocalObjectRef) DeepCopyInto(out *LocalObjectRef) {
	*out = *in
}

func (in *LocalObjectRef) DeepCopy() *LocalObjectRef {
	if in == nil {
		return nil
	}
	out := new(LocalObjectRef)
	in.DeepCopyInto(out)
	return out
}

func (in *TalosCluster) DeepCopyInto(out *TalosCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TalosCluster) DeepCopy() *TalosCluster {
	if in == nil {
		return nil
	}
	out := new(TalosCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *TalosCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TalosClusterList) DeepCopyInto(out *TalosClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TalosCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TalosClusterList) DeepCopy() *TalosClusterList {
	if in == nil {
		return nil
	}
	out := new(TalosClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *TalosClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TalosClusterSpec) DeepCopyInto(out *TalosClusterSpec) {
	*out = *in
	if in.NodeAddresses != nil {
		in, out := &in.NodeAddresses, &out.NodeAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CAPI != nil {
		in, out := &in.CAPI, &out.CAPI
		*out = new(CAPIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Lineage != nil {
		in, out := &in.Lineage, &out.Lineage
		*out = new(lineage.SealedCausalChain)
		**out = **in
	}
	if in.HardeningProfileRef != nil {
		in, out := &in.HardeningProfileRef, &out.HardeningProfileRef
		*out = new(LocalObjectRef)
		**out = **in
	}
}

func (in *TalosClusterSpec) DeepCopy() *TalosClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TalosClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TalosClusterStatus) DeepCopyInto(out *TalosClusterStatus) {
	*out = *in
	if in.CAPIClusterRef != nil {
		in, out := &in.CAPIClusterRef, &out.CAPIClusterRef
		*out = new(LocalObjectRef)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PkiExpiryDate != nil {
		in, out := &in.PkiExpiryDate, &out.PkiExpiryDate
		*out = (*in).DeepCopy()
	}
}

func (in *TalosClusterStatus) DeepCopy() *TalosClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TalosClusterStatus)
	in.DeepCopyInto(out)
	return out
}
